#!/bin/bash

#
# Installer for Pinky-server to the directory where it's called.
#
set -e

function read_install_questions() {
    # echo "This will build and install Pinky Server"
    # echo -n "Where would you like to install pinky-server? "
    # read  INSTALL_DIR
    # echo -n "Proceed with build? (y/n) "
    # read  YON
    # if [[ "$YON" == "y" || "$YON" == "yes" || "$YON" == "YES"  ]]; then
    #     echo "OK..."
    # else
    #     echo "Exiting"
    #     exit 2
    # fi
    echo "XXX: Installing to ${PWD}/pinky-server"
    echo "XXX: If you do not want this to happen then"
    echo "Control C now!"
    echo "sleeping 10 seconds"
    sleep 10
    INSTALL_DIR="${PWD}"
}

function do_install() {
    git clone http://github.com/ober/pinky-server && \
    cd ./pinky-server && \
    make 2>&1 && \
    useradd -s /bin/false -d "${INSTALL_DIR}"/pinky-server pinky && \
    chown -R pinky:pinky "${INSTALL_DIR}"/pinky-server && \
    su -s /bin/bash -c "cd ~/vendor/projects/pinky && \
      git checkout master && \
      git fetch && \
      git reset --hard origin/master && \
      luarocks make --local ./pinky-0.1-0.rockspec && \
      cd ~ && ./nginx/stop && ./nginx/start" pinky && \
      curl http://localhost:44444/pinky/disk
}

function update_pinky() {
    su -s /bin/bash -c "cd ~/vendor/projects/pinky && \
      git checkout master && \
      git fetch && \
      git reset --hard origin/master && \
      luarocks make --local ./pinky-0.1-0.rockspec && \
      cd ~ && ./nginx/stop && ./nginx/start" pinky && \
      curl http://localhost:44444/pinky/disk
}


function main(){
    read_install_questions && do_install
}

main
