#!/bin/bash

export PATH=$(pwd)/ngx_openresty/nginx/sbin:$HOME/.luarocks/bin:$PATH
export LUA_PATH="$HOME/.luarocks/share/lua/5.1/?.lua;;"

env PATH="$PATH" LUA_PATH="$LUA_PATH" nginx -p `pwd`/nginx/ -c nginx.conf
